<a href="https://colab.research.google.com/github/aparna2071/Layer-normalization-transformer/blob/main/layer_normalization_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch
from torch import nn

In [2]:
inputs=torch.Tensor([[[0.1,0.4,0.2],[0.6,0.5,0.1]]])
B,S,E=inputs.size()
inputs=inputs.reshape(S,B,E)
inputs.size()

torch.Size([2, 1, 3])

In [7]:
parameter_shape=inputs.size()[-2:]
gamma=nn.Parameter(torch.ones(parameter_shape))
beta=nn.Parameter(torch.zeros(parameter_shape))

In [9]:
gamma, beta

(Parameter containing:
 tensor([[1., 1., 1.]], requires_grad=True),
 Parameter containing:
 tensor([[0., 0., 0.]], requires_grad=True))

In [10]:
gamma.size(), beta.size()

(torch.Size([1, 3]), torch.Size([1, 3]))

In [11]:
dims=[-(i+1) for i in range(len(parameter_shape))]
dims

[-1, -2]

In [12]:
mean=inputs.mean(dim=dims,keepdim=True)
mean.size()

torch.Size([2, 1, 1])

In [21]:
mean

tensor([[[0.2333]],

        [[0.4000]]])

In [22]:
var=((inputs-mean)**2).mean(dim=dims,keepdim=True)
epsilon=1e-5
std=(var+epsilon).sqrt()  #epsilon is added because std is in deno so that deno don't become 0
std

tensor([[[0.1248]],

        [[0.2160]]])

In [23]:
y=(inputs-mean)/std
y

tensor([[[-1.0687,  1.3359, -0.2672]],

        [[ 0.9257,  0.4629, -1.3886]]])

In [25]:
out=gamma*y+beta
out

tensor([[[-1.0687,  1.3359, -0.2672]],

        [[ 0.9257,  0.4629, -1.3886]]], grad_fn=<AddBackward0>)

Class

In [27]:
import torch
from torch import nn

class LayerNormalization():
    def __init__(self, parameters_shape, eps=1e-5):
        self.parameters_shape=parameters_shape
        self.eps=eps
        self.gamma = nn.Parameter(torch.ones(parameters_shape))
        self.beta =  nn.Parameter(torch.zeros(parameters_shape))

    def forward(self, input):
        dims = [-(i + 1) for i in range(len(self.parameters_shape))]
        mean = inputs.mean(dim=dims, keepdim=True)
        print(f"Mean \n ({mean.size()}): \n {mean}")
        var = ((inputs - mean) ** 2).mean(dim=dims, keepdim=True)
        std = (var + self.eps).sqrt()
        print(f"Standard Deviation \n ({std.size()}): \n {std}")
        y = (inputs - mean) / std
        print(f"y \n ({y.size()}) = \n {y}")
        out = self.gamma * y  + self.beta
        print(f"out \n ({out.size()}) = \n {out}")
        return out


In [28]:
batch_size = 3
sentence_length = 5
embedding_dim = 8
inputs = torch.randn(sentence_length, batch_size, embedding_dim)

print(f"input \n ({inputs.size()}) = \n {inputs}")

input 
 (torch.Size([5, 3, 8])) = 
 tensor([[[ 0.7608,  0.0573,  1.2470, -0.6974,  2.3055, -0.9232, -2.3358,
          -1.3056],
         [ 1.4321, -0.5284, -0.6818,  0.1905, -0.0661, -0.3519,  0.6036,
          -0.5913],
         [ 0.6971, -2.5090, -1.1411, -0.9707, -0.5398,  1.6687, -1.1722,
           0.2297]],

        [[-0.5979, -1.6844,  1.0192,  0.0198, -0.3714,  0.3348,  1.3100,
           0.4670],
         [ 1.2634, -1.5431,  1.4209,  0.7463,  1.1878,  1.6404,  0.8545,
           0.0491],
         [ 0.2769, -1.0410,  1.3442, -1.6834,  0.1019, -0.6866,  0.3136,
           0.6992]],

        [[-0.2361,  1.0625,  1.1237, -0.1775, -0.6580,  0.4432, -1.0826,
          -1.0769],
         [ 0.2919,  0.2945, -1.0927, -0.1773, -0.7700,  0.7505,  0.8031,
          -0.9150],
         [ 0.6882, -1.2286,  1.8163,  0.2608,  0.4796, -0.8763, -2.0883,
           1.2136]],

        [[-0.1290,  1.7248, -0.5976, -0.6140, -0.0690, -0.0244, -0.2034,
          -0.8507],
         [ 1.4386,  1.4446, 